#include <iostream>
#include <vector>
#include <string>
#include <thread>
#include <chrono>
#include <algorithm>
#include <sstream>
#include <iomanip>
#include <map>
#include <set>
#include <functional>
#include <memory>
#include <cerrno>
#include <cctype>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <deque>
#include <stack>
#include <queue>
#include <tuple>
#include <utility>
#include <numeric>
#include <stdexcept>
#include <fstream>